Repository thullo/thullo-web, pull requests merged in 2023-03, with the labels that each got.

#38 Implement and consume attachment API
  src/actions/taskActions.ts
  src/components/AttachedItem.tsx
  src/components/Attachments.tsx
  src/components/DragDropCard.tsx
  src/components/ImageCache.tsx
  src/components/TaskModal.tsx
  src/services/boardService.ts
  src/services/fileService.ts
  src/services/taskService.ts
  src/services/userService.ts
  src/slice/boardSlice.ts
  src/utils/helperFn.ts
Labels: documentation

#41 Thullo 61 design the UI for displaying the board with different columns and team members based on the provided design
  .idea/sonarlint/issuestore/index.pb
  src/components/AddAnotherCardForm.tsx
  src/components/AddAnotherColumnForm.tsx
  src/components/DragAndDropBox.tsx
  src/components/InputComponent.tsx
  src/pages/user/BoardDetail.tsx
  src/slice/boardSlice.ts
Labels: enhancement

#43 implemented functionality of adding task cover image
  src/actions/taskActions.ts
  src/components/ImageCache.tsx
  src/components/TaskModal.tsx
  src/components/UnsplashModal.tsx
  src/services/taskService.ts
  src/slice/boardSlice.ts
Labels: enhancement

#44 THULLo-95: Refactor image size calculation in onSubmitSearchInputHandler
  src/components/ImageCache.tsx
  src/components/UnsplashModal.tsx
  src/services/taskService.ts
Labels: bug

#48 THULLO-104: Fix task image not showing after all active tabs is close on the broswer
  src/components/ImageCache.tsx
Labels: bug
