Repository thullo/thullo-web, pull requests merged in 2023-04, with the labels that each got.

#50 Thullo 52
  src/actions/boardAction.ts
  src/components/BoardItem.tsx
  src/components/EditBoardNameForm.tsx
  src/components/UpdateBoardDetailsModal.tsx
  src/pages/user/DashboardMain.tsx
  src/services/boardService.ts
  src/slice/boardSlice.ts
  tailwind.config.js
Labels: enhancement

#51 THULLO-88: Fix the displaying and closing of action section on task modal component
  src/components/AddMemberModal.tsx
  src/components/DragAndDropBox.tsx
  src/components/DragDropCard.tsx
  src/components/DragDropColumn.tsx
  src/components/LabelModal.tsx
  src/components/MembersList.tsx
  src/components/TaskModal.tsx
  src/components/UnsplashModal.tsx
Labels: enhancement

#52 Thullo 52
  src/actions/boardAction.ts
  src/components/BoardItem.tsx
  src/components/EditBoardNameForm.tsx
  src/components/UpdateBoardDetailsModal.tsx
  src/pages/user/DashboardMain.tsx
  src/services/boardService.ts
  src/slice/boardSlice.ts
  src/utils/types.ts
  tailwind.config.js
Labels: bug, enhancement

#53 implemented the readMe.md file
  README.md
  src/asset/img/Screenshot.jpg
  src/asset/img/add-board-screenshot.jpg
  src/asset/img/add-task-description-screenshot.jpg
  src/asset/img/add-task-screenshot.jpg
  src/asset/img/attachment-screenshot.jpg
  src/asset/img/board-details-screenshot.jpg
  src/asset/img/comment-screenshot.jpg
  src/asset/img/edit-board-screenshot-1.jpg
  src/asset/img/edit-board-screenshot-2.jpg
  src/asset/img/login-screenshot.jpg
  src/asset/img/signup-screenshot.jpg
  src/asset/img/view-task-screenshot.jpg
Labels: documentation, enhancement

#54 Thullo 110
  .idea/sonarlint/issuestore/index.pb
  src/actions/boardAction.ts
  src/actions/taskActions.ts
  src/components/AddAnotherCardForm.tsx
  src/components/AddAnotherColumnForm.tsx
  src/components/AddBoardModal.tsx
  src/components/Attachments.tsx
  src/components/BoardItem.tsx
  src/components/Btn.tsx
  src/components/DeleteWarningModal.tsx
  src/components/DragAndDropBox.tsx
  src/components/DragDropColumn.tsx
  src/components/EditBoardNameForm.tsx
  src/components/Input.tsx
  src/components/InputComponent.tsx
  src/components/Member.tsx
  src/components/Members.tsx
  src/components/Modal.tsx
  src/components/TaskModal.tsx
  src/components/ThreeDotModal.tsx
  src/components/UpdateBoardDetailsModal.tsx
  src/components/tsconfig.json
  src/pages/auth/ForgotPassword.tsx
  src/pages/auth/Login.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/SignUp.tsx
  src/pages/user/BoardDetail.tsx
  src/pages/user/ProfileEdit.tsx
  src/services/boardService.ts
  src/slice/boardSlice.ts
  src/utils/helperFn.ts
  src/utils/types.ts
Labels: documentation
